// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmmitClipboardText(arg1) {
  return window['go']['main']['App']['EmmitClipboardText'](arg1);
}

export function StartClipboardWatcher() {
  return window['go']['main']['App']['StartClipboardWatcher']();
}
