// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAllClipboardItems() {
  return window['go']['main']['App']['DeleteAllClipboardItems']();
}

export function DeleteOneByDateCreated(arg1) {
  return window['go']['main']['App']['DeleteOneByDateCreated'](arg1);
}

export function GetAllClipboardItems() {
  return window['go']['main']['App']['GetAllClipboardItems']();
}

export function GetLatestClipboardItem() {
  return window['go']['main']['App']['GetLatestClipboardItem']();
}
