// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EmmitClipboardText(arg1:main.ClipboardMessage):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function StartClipboardWatcher():Promise<void>;
