// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteAllClipboardItems():Promise<boolean>;

export function GetAllClipboardItems():Promise<Array<models.ClipboardItem>>;

export function GetLatestClipboardItem():Promise<Array<models.ClipboardItem>>;
